//metrics
###
GET http://localhost:8000/api/metrics

//getting all states
###
GET http://localhost:8000/api/state
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKb2huYXRoYWFuIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzE4MTU3NjUyfQ.YXuRcJeg6sygH569sWAMZ4Ytjf-RoXldYw3_CzQA820
//getting one state
###
GET  http://localhost:8000/api/state/8

// Deleting a state
###
DELETE  http://localhost:8000/api/state/4

//posting states/state
###
POST  http://localhost:8000/api/state
Content-Type: application/json

{ 
    "name": "Karen",
    "code": "4565"
}

//Cities
// getting cities 
###
GET http://localhost:8000/api/City


//posting cities
###
POST  http://localhost:8000/api/City
Content-Type: application/json

{   
    "name": "Nairobi",
     "state_Id": "1"
}


// Deleting a city
###
DELETE  http://localhost:8000/api/City/8


//restaurants

//getting all restaurants
###
GET http://localhost:8000/api/restaurant

//getting one restaurant
###
GET  http://localhost:8000/api/restaurant/2
###

DELETE  http://localhost:8000/api/restaurant/5

###
POST http://localhost:8000/api/restaurant
Content-Type: application/json

{ 
 "name": "Gilean",
  "street_address": "12345",
  "zip_code": "9999",
  "city_id": 2
}
//users app

### 
GET http://localhost:8000/api/users/2
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKb2huYXRoYWFuIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzE4MTU2Mzg0fQ.Yb9o2f6LJS13BQ2pmPt2ygeli2BO_dNKLS9JW2StRds
###
POST http://localhost:8000/api/users
Content-Type: application/json

{
  "name": "John Doe",
  "ccontact_Phone": "1234567890",
  "phone_Verified": true,
  "email": "john.doe@example.com",
  "email_Verified": true,
  "confirmation_Code": "ABC123",
  "password": "securepassword"
}
###
GET http://localhost:8000/api/users
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKb2huYXRoYWFuIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzE4MTU2Mzg0fQ.Yb9o2f6LJS13BQ2pmPt2ygeli2BO_dNKLS9JW2StRds

//status_catalog


### 
GET http://localhost:8000/api/status_catalog

###
POST http://localhost:8000/api/status_catalog
Content-Type: application/json

{
  "name": "Gilean"
}
           // category
###
GET http://localhost:8000/api/category

//getting one category
###
GET  http://localhost:8000/api/category/

// Deleting a category
###
DELETE  http://localhost:8000/api/category/3

###
//posting states/category
POST  http://localhost:8000/api/category
Content-Type: application/json

{    
    "name": "Karen"
    
}

//getting all menu_item
###
GET http://localhost:8000/api/menu_item/

//getting one menuitem
###
GET  http://localhost:8000/api/menu_item/1

// Deleting a menuitem
###
DELETE  http://localhost:8000/api/menu_item/13

###
//posting menuitem
POST  http://localhost:8000/api/menu_item
Content-Type: application/json

{ 
    "name": "muli",
    "restaurantId" : 2,
    "categoryId": 4,
    "description": "good",
    "ingredients": "wheat",
    "price": 2344,
    "active": true
}



//getting all driver
###
GET http://localhost:8000/api/driver

//getting one driver
###
GET  http://localhost:8000/api/driver/2

// Deleting a driver
###
DELETE  http://localhost:8000/api/driver/

###
//posting driver
POST  http://localhost:8000/api/driver
Content-Type: application/json

{ 
  "car_make": "Toyota",
  "car_model": "Toyota",
  "car_year": "2017",
  "user_id": 3,
  "online": false,
  "delivering": true
}

###
GET http://localhost:8000/api/driverordersRelationships

//getting all address
###
GET http://localhost:8000/api/address

//getting oneaddress
###
GET  http://localhost:8000/api/address/1

// Deleting aaddress
###
DELETE  http://localhost:8000/api/address

###
//posting address
POST  http://localhost:8000/api/address
Content-Type: application/json

{ 
    
  "street_Address1": "77AW",
  "street_Address2": "27zs",
  "zip_Code": "4565",
  "delivery_Instructions": "delicate",
  "user_Id": 3,
  "city_Id": 1
}

//getting all drestaurant_owner
###
GET http://localhost:8000/api/restaurant_owner

//getting one restaurant_owner
###
GET  http://localhost:8000/api/restaurant_owner/4

// Deleting a restaurant_owner
###
DELETE  http://localhost:8000/api/restaurant_owner/5

###
//posting restaurant_owner
POST  http://localhost:8000/api/restaurant_owner
Content-Type: application/json

{ 
    "restaurantId": 3,
    "ownerId": 3
}

###
GET http://localhost:8000/api/orders

//getting one orders
###
GET  http://localhost:8000/api/orders/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYW4iLCJyb2xlIjoidXNlciIsImV4cCI6MTcxODE5MzEwNH0.0fo1OyaSUewxkc6ve8BmD4IeXn1Lr3ZqZjKwBW2ydo8

// Deleting aorders
###
DELETE  http://localhost:8000/api/orders/5

###
//posting orders
POST  http://localhost:8000/api/orders
Content-Type: application/json

{ 
    "restaurant_Id": 4,
    "delivery_Address_Id": 3,
    "user_Id": 3,
    "driver_Id": 4,
    "price": 5000,
    "discount": 1000,
    "final_Price": 4000,
    "comment": "nice service" 
}


//COMMENT

###
GET http://localhost:8000/api/comment

//getting one comment
###
GET  http://localhost:8000/api/comment/4

// Deleting a comment
###
DELETE  http://localhost:8000/api/comment/5

###
//posting comment
POST  http://localhost:8000/api/comment
Content-Type: application/json

{ 
    "order_id": 7,
    "user_id": 5,
    "comment_text": "Thank you for your good service",
    "is_complaint": true,
    "is_price": true

}

//order_status

###
GET http://localhost:8000/api/order_status

//getting one order_status
###
GET  http://localhost:8000/api/order_status/4

// Deleting a order_status
###
DELETE  http://localhost:8000/api/order_status/5

###
//posting order_status
POST  http://localhost:8000/api/order_status
Content-Type: application/json

{ 
    "orderId": 7,
    "statusCatalogId": 2
}

//order_menu_item

###
GET http://localhost:8000/api/order_menu_item
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKb2huYXRoYWFuIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzE4MTU3NjUyfQ.YXuRcJeg6sygH569sWAMZ4Ytjf-RoXldYw3_CzQA820
//getting one order_status
###
GET  http://localhost:8000/api/order_menu_item/4

// Deleting a order_status
###
DELETE  http://localhost:8000/api/order_menu_item/5

###
//posting order_status
POST  http://localhost:8000/api/order_menu_item
Content-Type: application/json

{ 
    "order_Id": 8,
    "menuItem_Id": 8,
    "quantity": 4555,
    "itemPrice": "4564",
    "price": "3049",
    "comment": "for lunch"
}




// Authentication
###
//posting auth_on_users
POST  http://localhost:8000/api/auth/register
Content-Type: application/json

{
    "userId": 2,
    "username": "Mannu", 
    "password": "doean123",
    "role": "user"
}
###
//loging in auth_on_users
POST  http://localhost:8000/api/auth/login
Content-Type: application/json

{
   "username": "Mannu", 
   "password": "doean123"
}

###
GET  http://localhost:8000/api/users/3
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYW5udSIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzE4MTk3MDU4fQ.bF5zBRer3xbIzMAxaAu5RgYqRYzaTOlb1653L9W5u0o